{{- if .Values.pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "helper.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc }}
{{- end }}
