apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helper.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helper.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  resourceNames:
  - {{ include "helper.fullname" . }}
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helper.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helper.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "helper.fullname" . }}
    namespace: {{ .Release.Namespace }}
