apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.fullname" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k, $v := .Values.env }}
  {{ $k | quote }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
